import { createVerify, createPublicKey } from 'crypto';
import { generateHardwareId } from './hardware';
import { queryOne, executeWrite } from './database';

// Public key for license verification (RSA-2048, PEM format)
// This key is generated by scripts/license-gen.ts and embedded here
// NEVER expose the private key in the app
const PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----
REPLACE_WITH_GENERATED_PUBLIC_KEY
-----END PUBLIC KEY-----`;

export const PREMIUM_FEATURES = [
  'whatsapp',
  'legacy_import',
  'multi_company',
  'backup',
  'print_pdf'
] as const;

export type PremiumFeature = typeof PREMIUM_FEATURES[number];

export interface LicensePayload {
  customer: string;
  type: 'perpetual' | 'subscription';
  features: PremiumFeature[];
  activations_max: number;
  expiry: string | null; // ISO date string, null for perpetual
  issued: string; // ISO date string
}

export interface LicenseStatus {
  valid: boolean;
  type: 'trial' | 'perpetual' | 'subscription' | 'none';
  customer?: string;
  features: PremiumFeature[];
  expiry?: string;
  daysLeft?: number;
  activationsUsed: number;
  activationsMax: number;
  trialDaysLeft: number;
  error?: string;
}

// Decode base64url
function base64UrlDecode(str: string): Buffer {
  const base64 = str.replace(/-/g, '+').replace(/_/g, '/');
  const padded = base64 + '='.repeat((4 - base64.length % 4) % 4);
  return Buffer.from(padded, 'base64');
}

// Encode base64url
function base64UrlEncode(buf: Buffer): string {
  return buf.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

// Parse a license key string
function parseLicenseKey(key: string): { payload: LicensePayload; signature: Buffer } | null {
  const cleaned = key.trim();
  if (!cleaned.startsWith('LM-')) return null;

  const parts = cleaned.substring(3).split('.');
  if (parts.length !== 2) return null;

  try {
    const payloadBuf = base64UrlDecode(parts[0]);
    const payload: LicensePayload = JSON.parse(payloadBuf.toString('utf-8'));
    const signature = base64UrlDecode(parts[1]);
    return { payload, signature };
  } catch {
    return null;
  }
}

// Verify license signature
function verifySignature(payload: LicensePayload, signature: Buffer): boolean {
  try {
    const publicKeyObj = createPublicKey(PUBLIC_KEY);
    const data = JSON.stringify(payload);
    const verifier = createVerify('RSA-SHA256');
    verifier.update(data);
    return verifier.verify(publicKeyObj, signature);
  } catch {
    return false;
  }
}

// Check if trial is active
function getTrialStartDate(): string | null {
  const result = queryOne<{ value: string }>(
    "SELECT value FROM settings WHERE key = 'trial_start_date'"
  );
  return result?.value || null;
}

function startTrial(): string {
  const now = new Date().toISOString();
  executeWrite(
    "INSERT OR REPLACE INTO settings (key, value) VALUES ('trial_start_date', ?)",
    [now]
  );
  return now;
}

function calculateTrialDaysLeft(startDate: string): number {
  const start = new Date(startDate);
  const now = new Date();
  const diffMs = start.getTime() + 30 * 24 * 60 * 60 * 1000 - now.getTime();
  return Math.max(0, Math.ceil(diffMs / (1000 * 60 * 60 * 24)));
}

// Get stored license from database
function getStoredLicense(): { key: string; hardware_id: string } | null {
  return queryOne<{ key: string; hardware_id: string }>(
    'SELECT key, hardware_id FROM licenses ORDER BY id DESC LIMIT 1'
  ) || null;
}

// Main function: verify a license key
export function verifyLicense(key: string): { valid: boolean; payload?: LicensePayload; error?: string } {
  const parsed = parseLicenseKey(key);
  if (!parsed) {
    return { valid: false, error: 'Invalid license key format' };
  }

  const { payload, signature } = parsed;

  // Verify signature
  if (!verifySignature(payload, signature)) {
    return { valid: false, error: 'Invalid license signature' };
  }

  // Check expiry for subscriptions
  if (payload.type === 'subscription' && payload.expiry) {
    const expiryDate = new Date(payload.expiry);
    if (expiryDate < new Date()) {
      return { valid: false, error: 'License has expired' };
    }
  }

  // Check hardware binding
  const hardwareId = generateHardwareId();
  const storedLicense = getStoredLicense();
  if (storedLicense && storedLicense.hardware_id) {
    // Already activated on a different machine
    if (storedLicense.hardware_id !== hardwareId) {
      return { valid: false, error: 'License is bound to a different machine' };
    }
  }

  return { valid: true, payload };
}

// Activate a license key
export function activateLicense(key: string): { success: boolean; error?: string } {
  const verification = verifyLicense(key);
  if (!verification.valid || !verification.payload) {
    return { success: false, error: verification.error };
  }

  const { payload } = verification;
  const hardwareId = generateHardwareId();

  // Check activation count
  const existing = queryOne<{ activations_used: number }>(
    'SELECT COUNT(*) as activations_used FROM license_activations WHERE license_key = ?',
    [key]
  );
  const used = existing?.activations_used || 0;

  if (used >= payload.activations_max) {
    return { success: false, error: `Activation limit reached (${payload.activations_max} max)` };
  }

  // Check if this machine is already activated
  const thisMachine = queryOne<{ id: number }>(
    'SELECT id FROM license_activations WHERE license_key = ? AND hardware_id = ?',
    [key, hardwareId]
  );

  if (!thisMachine) {
    // Record this activation
    executeWrite(
      'INSERT INTO license_activations (license_key, hardware_id, activated_at) VALUES (?, ?, ?)',
      [key, hardwareId, new Date().toISOString()]
    );
  }

  // Store the license
  executeWrite(
    "INSERT INTO licenses (key, hardware_id, customer_name, license_type, activated_at) VALUES (?, ?, ?, ?, ?)",
    [key, hardwareId, payload.customer, payload.type, new Date().toISOString()]
  );

  return { success: true };
}

// Get current license status
export function getLicenseStatus(): LicenseStatus {
  const hardwareId = generateHardwareId();

  // Check for stored license
  const stored = getStoredLicense();
  if (stored) {
    const verification = verifyLicense(stored.key);
    if (verification.valid && verification.payload) {
      const payload = verification.payload;
      const activations = queryOne<{ count: number }>(
        'SELECT COUNT(*) as count FROM license_activations WHERE license_key = ?',
        [stored.key]
      );

      let daysLeft: number | undefined;
      if (payload.type === 'subscription' && payload.expiry) {
        const expiryDate = new Date(payload.expiry);
        const now = new Date();
        daysLeft = Math.max(0, Math.ceil((expiryDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24)));
      }

      return {
        valid: true,
        type: payload.type,
        customer: payload.customer,
        features: payload.features,
        expiry: payload.expiry || undefined,
        daysLeft,
        activationsUsed: activations?.count || 0,
        activationsMax: payload.activations_max,
        trialDaysLeft: 0
      };
    }
  }

  // No valid license — check trial
  const trialStart = getTrialStartDate();
  if (!trialStart) {
    // Start trial now
    startTrial();
    return {
      valid: false,
      type: 'trial',
      features: PREMIUM_FEATURES as unknown as PremiumFeature[],
      activationsUsed: 0,
      activationsMax: 0,
      trialDaysLeft: 30
    };
  }

  const trialDaysLeft = calculateTrialDaysLeft(trialStart);
  return {
    valid: false,
    type: 'trial',
    activationsUsed: 0,
    activationsMax: 0,
    trialDaysLeft
  };
}

// Check if a specific premium feature is available
export function isPremiumFeature(feature: string): boolean {
  const status = getLicenseStatus();

  // During trial, all features are available
  if (status.type === 'trial' && status.trialDaysLeft > 0) {
    return true;
  }

  // With valid license, check feature list
  if (status.valid) {
    return status.features.includes(feature as PremiumFeature);
  }

  return false;
}

// Get list of premium features for the UI
export function getPremiumFeatureList(): Array<{ id: string; name: string; description: string }> {
  return [
    { id: 'whatsapp', name: 'WhatsApp Integration', description: 'Send invoices and receipts via WhatsApp' },
    { id: 'legacy_import', name: 'Legacy Import', description: 'Import data from Speed Plus MDB files' },
    { id: 'multi_company', name: 'Multi-Company', description: 'Manage multiple companies' },
    { id: 'backup', name: 'Backup & Restore', description: 'Export and import database backups' },
    { id: 'print_pdf', name: 'Print & PDF', description: 'Print and save documents as PDF' }
  ];
}
